version: 2.0 # use CircleCI 2.0

base_image: &base_image hashicorp/terraform:light

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      terraform init

jobs:
  terraform_plan:
    docker:
      - image: *base_image
    steps:
      - run:
          name: pwd
          command: |
            pwd
      - *terraform_init
      - run:
          name: Terraform Plan
          command: |
            terraform plan
workflows:
  version: 2
  build_all:
    jobs:
      - terraform_plan:
          filters:
            branches:
              ignore:
                - master