version: 2.0 # use CircleCI 2.0

base_image: &base_image hashicorp/terraform:light

set_aws_credentials: &set_aws_credentials
  run:
    name: Set aws credentials
    command: |
      mkdir ~/.aws
      echo "
        [default]
        aws_access_key_id=$AWS_ACCESS_KEY_ID
        aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
      " > ~/.aws/credentials

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      terraform init -backend-config="token=${TF_API_TOKEN}"

jobs:
  terraform_plan:
    docker:
      - image: *base_image
    steps:
      - *set_aws_credentials
      - checkout
      - run:
          name: cat
          command: |
            cat ~/.aws/credentials
      - run:
          name: list
          command: |
            ls -l
      - *terraform_init
      - run:
          name: Terraform Plan
          command: |
            terraform plan
workflows:
  version: 2
  build_all:
    jobs:
      - terraform_plan:
          filters:
            branches:
              ignore:
                - master